#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════
# SinaiCamps — One-Command Setup, Test & Deploy
# ═══════════════════════════════════════════════════════════
# Usage:
#   ./setup.sh              — interactive setup (first time)
#   ./setup.sh deploy       — skip setup, just deploy
#   ./setup.sh test         — skip setup, just run all tests
#   ./setup.sh e2e          — run Playwright E2E tests
#   ./setup.sh status       — check Cloudflare auth & show project status
# ═══════════════════════════════════════════════════════════

set -eo pipefail
export NODE_OPTIONS="--dns-result-order=ipv4first"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
START_TIME=$(date +%s)

# ─── Colors ───────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log()   { echo -e "${GREEN}[$(date +%H:%M:%S)]${NC} $*"; }
warn()  { echo -e "${YELLOW}[$(date +%H:%M:%S)] ⚠️  $*${NC}"; }
err()   { echo -e "${RED}[$(date +%H:%M:%S)] ❌ $*${NC}"; }
ok()    { echo -e "${GREEN}[$(date +%H:%M:%S)] ✅ $*${NC}"; }
info()  { echo -e "${CYAN}$*${NC}"; }
section() { echo ""; echo -e "${BOLD}════════════════════════════════════════${NC}"; echo -e "${BOLD}  $*${NC}"; echo -e "${BOLD}════════════════════════════════════════${NC}"; }
elapsed() { echo "$(( $(date +%s) - START_TIME ))s"; }

# ─── Load .env if exists ──────────────────────────────────
load_env() {
  if [ -f "$ENV_FILE" ]; then
    log "Loading .env from $ENV_FILE"
    set -a
    source "$ENV_FILE"
    set +a
  fi
}

# ─── Save .env ────────────────────────────────────────────
save_env() {
  local token="$1"
  local account_id="$2"
  cat > "$ENV_FILE" <<EOF
# SinaiCamps Cloudflare Credentials
# Generated by setup.sh on $(date -Iseconds)
CLOUDFLARE_API_TOKEN=$token
CLOUDFLARE_ACCOUNT_ID=$account_id
EOF
  chmod 600 "$ENV_FILE"
  log "Credentials saved to $ENV_FILE (mode 600)"
}

# ═══════════════════════════════════════════════════════════
# STEP 1: Check / Setup Cloudflare Credentials
# ═══════════════════════════════════════════════════════════
setup_cloudflare() {
  section "Step 1: Cloudflare Authentication"

  load_env

  # Check if credentials are already valid
  if [ -n "${CLOUDFLARE_API_TOKEN:-}" ] && [ "$CLOUDFLARE_API_TOKEN" != "your_cloudflare_api_token" ]; then
    local account_id="${CLOUDFLARE_ACCOUNT_ID:-}"
    if [ -n "$account_id" ] && [ "$account_id" != "your_cloudflare_account_id" ]; then
      # Verify the token works
      local api_response
      if api_response=$(curl -sf --max-time 10 \
        -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
        "https://api.cloudflare.com/client/v4/user" 2>/dev/null); then
        local email
        email=$(echo "$api_response" | grep -o '"email":"[^"]*"' | head -1 | cut -d'"' -f4)
        ok "Authenticated as: ${email:-unknown}"
        ok "Account ID: $account_id"
        return 0
      else
        warn "Saved credentials are invalid or expired. Let's set them up again."
      fi
    fi
  fi

  echo ""
  info "╔══════════════════════════════════════════════════════════╗"
  info "║  Cloudflare credentials not found or invalid.           ║"
  info "║                                                         ║"
  info "║  You need:                                              ║"
  info "║  1. A Cloudflare API Token with Workers/D1/Pages perms  ║"
  info "║  2. Your Cloudflare Account ID                          ║"
  info "╚══════════════════════════════════════════════════════════╝"
  echo ""

  # Option A: Use wrangler login (browser-based OAuth)
  info "Choose how to authenticate:"
  echo ""
  echo -e "  ${BOLD}1)${NC} Browser login (opens Cloudflare dashboard)"
  echo -e "  ${BOLD}2)${NC} Paste API Token + Account ID manually"
  echo -e "  ${BOLD}3)${NC} I already have them in environment variables"
  echo ""

  read -rp "Choice [1-3]: " auth_choice

  case "$auth_choice" in
    1)
      browser_login
      ;;
    2)
      manual_setup
      ;;
    3)
      if [ -z "${CLOUDFLARE_API_TOKEN:-}" ] || [ "$CLOUDFLARE_API_TOKEN" = "your_cloudflare_api_token" ]; then
        err "CLOUDFLARE_API_TOKEN is not set. Choose option 2 to set it up."
        setup_cloudflare
        return
      fi
      log "Using existing environment variables"
      ;;
    *)
      err "Invalid choice"
      setup_cloudflare
      return
      ;;
  esac

  # Final verification
  verify_cloudflare_auth
}

browser_login() {
  info "Opening Cloudflare dashboard for browser-based login..."
  echo ""

  # Wrangler uses its own OAuth flow
  cd "$SCRIPT_DIR/backend"
  npm install --no-audit --no-fund --prefer-offline 2>&1 | tail -3

  info "This will open your browser. Log in to Cloudflare, then come back here."
  echo ""

  # Run wrangler login — this does browser OAuth
  if npx wrangler login 2>&1; then
    ok "Wrangler login successful!"
  else
    warn "Wrangler browser login failed or was cancelled."
    warn "Falling back to manual setup..."
    manual_setup
    return
  fi

  cd "$SCRIPT_DIR"

  # Now get account ID from wrangler's stored credentials
  info "Fetching your Account ID..."
  local whoami_output
  if whoami_output=$(curl -sf --max-time 10 \
    -H "Authorization: Bearer $(cat ~/.wrangler/config/default.toml 2>/dev/null | grep api_token | cut -d'"' -f2)" \
    "https://api.cloudflare.com/client/v4/accounts?per_page=1" 2>/dev/null); then
    local account_id
    account_id=$(echo "$whoami_output" | grep -o '"id":"[^"]*"' | head -1 | cut -d'"' -f4)
    if [ -n "$account_id" ]; then
      # Extract the API token from wrangler config
      local api_token
      api_token=$(grep api_token ~/.wrangler/config/default.toml 2>/dev/null | cut -d'"' -f2 || echo "")
      if [ -n "$api_token" ]; then
        save_env "$api_token" "$account_id"
        export CLOUDFLARE_API_TOKEN="$api_token"
        export CLOUDFLARE_ACCOUNT_ID="$account_id"
        return 0
      fi
    fi
  fi

  warn "Could not auto-detect Account ID from wrangler login."
  warn "Please provide it manually."
  manual_account_id
}

manual_setup() {
  echo ""
  info "━━━ How to get your API Token ━━━"
  echo ""
  echo -e "  1. Go to: ${BLUE}https://dash.cloudflare.com/profile/api-tokens${NC}"
  echo -e "  2. Click ${BOLD}\"Create Token\"${NC}"
  echo -e "  3. Use the ${BOLD}\"Edit Cloudflare Workers\"${NC} template"
  echo -e "  4. Or create custom with these permissions:"
  echo -e "     - ${GREEN}Account > Workers Runtimes > Edit${NC}"
  echo -e "     - ${GREEN}Account > D1 > Edit${NC}"
  echo -e "     - ${GREEN}Account > Pages > Edit${NC}"
  echo -e "     - ${GREEN}Zone > DNS > Edit${NC} (for sinaicamps.com)"
  echo -e "  5. Copy the token and paste below"
  echo ""

  local token=""
  while [ -z "$token" ]; do
    read -rsp "Paste your Cloudflare API Token: " token
    echo ""
    if [ -z "$token" ]; then
      err "Token cannot be empty. Press Ctrl+C to abort."
    fi
  done

  # Verify token
  log "Verifying token..."
  local user_resp
  if user_resp=$(curl -sf --max-time 10 \
    -H "Authorization: Bearer $token" \
    "https://api.cloudflare.com/client/v4/user" 2>/dev/null); then
    local email
    email=$(echo "$user_resp" | grep -o '"email":"[^"]*"' | head -1 | cut -d'"' -f4)
    ok "Token valid! Authenticated as: $email"
  else
    err "Token verification failed. Please check the token."
    manual_setup
    return
  fi

  # Get Account ID
  info ""
  info "━━━ How to get your Account ID ━━━"
  echo ""
  echo -e "  Go to: ${BLUE}https://dash.cloudflare.com${NC}"
  echo -e "  Your Account ID is in the ${BOLD}right sidebar${NC} of the Overview page."
  echo ""

  local account_id=""
  while [ -z "$account_id" ]; do
    read -rsp "Paste your Cloudflare Account ID: " account_id
    echo ""
    if [ -z "$account_id" ]; then
      err "Account ID cannot be empty. Press Ctrl+C to abort."
    fi
  done

  save_env "$token" "$account_id"
  export CLOUDFLARE_API_TOKEN="$token"
  export CLOUDFLARE_ACCOUNT_ID="$account_id"
}

manual_account_id() {
  local account_id=""
  while [ -z "$account_id" ]; do
    read -rsp "Paste your Cloudflare Account ID: " account_id
    echo ""
  done

  local token="${CLOUDFLARE_API_TOKEN:-}"
  save_env "$token" "$account_id"
  export CLOUDFLARE_ACCOUNT_ID="$account_id"
}

verify_cloudflare_auth() {
  section "Verifying Cloudflare Access"

  if [ -z "${CLOUDFLARE_API_TOKEN:-}" ] || [ -z "${CLOUDFLARE_ACCOUNT_ID:-}" ]; then
    err "Missing credentials"
    exit 1
  fi

  # Test user endpoint
  local user_resp
  if user_resp=$(curl -sf --max-time 10 \
    -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
    "https://api.cloudflare.com/client/v4/user" 2>/dev/null); then
    local email
    email=$(echo "$user_resp" | grep -o '"email":"[^"]*"' | head -1 | cut -d'"' -f4)
    ok "API Token valid — $email"
  else
    err "API Token is invalid"
    exit 1
  fi

  # Test account endpoint
  local acct_resp
  if acct_resp=$(curl -sf --max-time 10 \
    -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
    "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID" 2>/dev/null); then
    local acct_name
    acct_name=$(echo "$acct_resp" | grep -o '"name":"[^"]*"' | head -1 | cut -d'"' -f4)
    ok "Account accessible — ${acct_name:-$CLOUDFLARE_ACCOUNT_ID}"
  else
    err "Cannot access account $CLOUDFLARE_ACCOUNT_ID"
    err "Check that the Account ID is correct and your token has permissions."
    exit 1
  fi

  # Test D1 access
  local d1_resp
  if d1_resp=$(curl -sf --max-time 10 \
    -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
    "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/d1/database" 2>/dev/null); then
    local db_count
    db_count=$(echo "$d1_resp" | grep -o '"name":"campmaster-db"' | wc -l)
    if [ "$db_count" -gt 0 ]; then
      ok "D1 database 'campmaster-db' found"
    else
      warn "D1 databases found but 'campmaster-db' not detected. Deploy may create it."
    fi
  else
    warn "Could not verify D1 access (may still work during deploy)"
  fi

  ok "All Cloudflare checks passed!"
}

# ═══════════════════════════════════════════════════════════
# STEP 2: Install Dependencies
# ═══════════════════════════════════════════════════════════
install_deps() {
  section "Step 2: Installing Dependencies"

  load_env

  log "Root..."
  cd "$SCRIPT_DIR" && npm install --no-audit --no-fund 2>&1 | tail -3

  log "Backend..."
  cd "$SCRIPT_DIR/backend" && npm install --no-audit --no-fund 2>&1 | tail -3

  log "App..."
  cd "$SCRIPT_DIR/app" && npm install --no-audit --no-fund 2>&1 | tail -3

  cd "$SCRIPT_DIR"
  ok "All dependencies installed"
}

# ═══════════════════════════════════════════════════════════
# STEP 3: Run Tests
# ═══════════════════════════════════════════════════════════
run_tests() {
  section "Step 3: Running Tests"

  load_env

  log "Backend unit tests..."
  cd "$SCRIPT_DIR/backend" && npx vitest run 2>&1 | tail -5
  local backend_exit=$?
  cd "$SCRIPT_DIR"

  log "App unit tests..."
  cd "$SCRIPT_DIR/app" && npx vitest run 2>&1 | tail -5
  local app_exit=$?
  cd "$SCRIPT_DIR"

  if [ $backend_exit -ne 0 ] || [ $app_exit -ne 0 ]; then
    err "Some tests failed!"
    return 1
  fi

  ok "All unit tests passed"
}

# ═══════════════════════════════════════════════════════════
# STEP 4: Deploy
# ═══════════════════════════════════════════════════════════
run_deploy() {
  section "Step 4: Deploying to Cloudflare"

  load_env

  # Export credentials for deploy.sh
  export CLOUDFLARE_API_TOKEN="${CLOUDFLARE_API_TOKEN:-}"
  export CLOUDFLARE_ACCOUNT_ID="${CLOUDFLARE_ACCOUNT_ID:-}"

  if [ -z "$CLOUDFLARE_API_TOKEN" ] || [ "$CLOUDFLARE_API_TOKEN" = "your_cloudflare_api_token" ]; then
    err "Cloudflare credentials not set. Run './setup.sh' first."
    exit 1
  fi

  bash "$SCRIPT_DIR/deploy.sh" "$@"
}

# ═══════════════════════════════════════════════════════════
# STEP 5: Run E2E Tests (Playwright)
# ═══════════════════════════════════════════════════════════
run_e2e() {
  section "Step 5: Running Playwright E2E Tests"

  load_env

  cd "$SCRIPT_DIR"
  log "Starting Playwright (spins up backend + frontend automatically)..."
  log "Projects: marketplace, tenant, admin, auth, cross-cutting, pos"
  echo ""

  npx playwright test --reporter=list 2>&1
}

# ═══════════════════════════════════════════════════════════
# STATUS CHECK
# ═══════════════════════════════════════════════════════════
show_status() {
  section "Project Status"
  load_env

  # Cloudflare auth
  echo -e "\n${BOLD}Cloudflare:${NC}"
  if [ -n "${CLOUDFLARE_API_TOKEN:-}" ] && [ "$CLOUDFLARE_API_TOKEN" != "your_cloudflare_api_token" ]; then
    local user_resp
    if user_resp=$(curl -sf --max-time 10 \
      -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
      "https://api.cloudflare.com/client/v4/user" 2>/dev/null); then
      local email
      email=$(echo "$user_resp" | grep -o '"email":"[^"]*"' | head -1 | cut -d'"' -f4)
      echo -e "  Auth:   ${GREEN}✅ Authenticated${NC} ($email)"
      echo -e "  Account: $CLOUDFLARE_ACCOUNT_ID"
    else
      echo -e "  Auth:   ${RED}❌ Invalid token${NC}"
    fi
  else
    echo -e "  Auth:   ${YELLOW}⚠️  Not configured${NC} — run './setup.sh'"
  fi

  # Production status
  echo -e "\n${BOLD}Production:${NC}"
  local api_resp
  if api_resp=$(curl -sf --max-time 10 "https://api.sinaicamps.com/api/tenants" 2>/dev/null); then
    if echo "$api_resp" | grep -q '"success"'; then
      echo -e "  API:    ${GREEN}✅ Online${NC} (api.sinaicamps.com)"
    else
      echo -e "  API:    ${YELLOW}⚠️  Responding but unexpected format${NC}"
    fi
  else
    echo -e "  API:    ${RED}❌ Offline or unreachable${NC}"
  fi

  local frontend_resp
  if frontend_resp=$(curl -sf --max-time 10 -o /dev/null -w "%{http_code}" "https://sinaicamps.com" 2>/dev/null); then
    if [ "$frontend_resp" = "200" ]; then
      echo -e "  Frontend: ${GREEN}✅ Online${NC} (sinaicamps.com — HTTP $frontend_resp)"
    else
      echo -e "  Frontend: ${YELLOW}⚠️  HTTP $frontend_resp${NC}"
    fi
  else
    echo -e "  Frontend: ${RED}❌ Unreachable${NC}"
  fi

  # Node.js version
  echo -e "\n${BOLD}Environment:${NC}"
  echo -e "  Node:   $(node --version)"
  echo -e "  npm:    $(npm --version)"

  # Wrangler version (backend)
  if [ -f "$SCRIPT_DIR/backend/node_modules/.bin/wrangler" ]; then
    local wrangler_ver
    wrangler_ver=$(cd "$SCRIPT_DIR/backend" && npx wrangler --version 2>/dev/null || echo "not installed")
    echo -e "  Wrangler: $wrangler_ver"
  fi

  # Backup count
  if [ -d "$SCRIPT_DIR/backups" ]; then
    local backup_count
    backup_count=$(ls "$SCRIPT_DIR/backups/"*.sql 2>/dev/null | wc -l)
    echo -e "\n${BOLD}Backups:${NC} $backup_count SQL files"
  fi
}

# ═══════════════════════════════════════════════════════════
# FULL INTERACTIVE FLOW
# ═══════════════════════════════════════════════════════════
full_setup() {
  echo -e "${BOLD}"
  echo "╔══════════════════════════════════════════════════════╗"
  echo "║        🏕️  SinaiCamps Setup & Deploy               ║"
  echo "║        sinaicamps.com                              ║"
  echo "╚══════════════════════════════════════════════════════╝"
  echo -e "${NC}"

  setup_cloudflare
  install_deps
  run_tests

  echo ""
  info "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  info "  Setup complete! Next steps:"
  info ""
  info "  Deploy to production:   ./setup.sh deploy"
  info "  Run E2E tests:          ./setup.sh e2e"
  info "  Check status:           ./setup.sh status"
  info ""
  info "  Total time: $(elapsed)"
  info "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
}

# ═══════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════
MODE="${1:-setup}"

case "$MODE" in
  setup|first)
    full_setup
    ;;
  deploy)
    run_deploy "${@:2}"
    ;;
  test)
    load_env
    run_tests
    ;;
  e2e)
    run_e2e
    ;;
  status)
    show_status
    ;;
  --help|-h)
    echo "Usage: ./setup.sh [command]"
    echo ""
    echo "Commands:"
    echo "  (none)    Interactive setup — Cloudflare auth, install, test"
    echo "  deploy    Deploy to Cloudflare (production)"
    echo "  test      Run unit tests only"
    echo "  e2e       Run Playwright E2E tests"
    echo "  status    Show project & Cloudflare status"
    echo ""
    echo "Deploy options (passed to deploy.sh):"
    echo "  --backend    Backend only"
    echo "  --frontend   Frontend only"
    echo "  --migrate    Migrations only"
    echo "  --staging    Deploy to staging"
    ;;
  *)
    err "Unknown command: $MODE"
    echo "Run './setup.sh --help' for usage."
    exit 1
    ;;
esac
