export const POS = {
  login: {
    identifierInput: 'input[name="identifier"], input[placeholder*="admin"]',
    passwordInput: 'input[type="password"]',
    submitBtn: 'button:has-text("Sign In"), button[type="submit"]',
    cardTitle: '.ant-card:has-text("SinaiCamps POS")',
    errorMessage: '.ant-message-error',
    successMessage: '.ant-message-success',
  },
  nav: {
    sider: '.ant-layout-sider',
    menuItems: '.ant-menu-item',
    dashboardLink: '.ant-menu-item:has-text("Dashboard")',
    productsLink: '.ant-menu-item:has-text("Products")',
    ordersLink: '.ant-menu-item:has-text("Orders")',
    customersLink: '.ant-menu-item:has-text("Customers")',
    inventoryLink: '.ant-menu-item:has-text("Inventory")',
    staffLink: '.ant-menu-item:has-text("Staff")',
    reportsLink: '.ant-menu-item:has-text("Reports")',
    userDropdown: '.ant-dropdown-trigger',
    logoutBtn: '.ant-dropdown-menu-item:has-text("Logout")',
  },
  dashboard: {
    revenueCard: '.ant-statistic:has-text("Revenue")',
    ordersCard: '.ant-statistic:has-text("Orders")',
    productsSoldCard: '.ant-statistic:has-text("Products Sold")',
    lowStockCard: '.ant-statistic:has-text("Low Stock")',
    recentOrdersCard: '.ant-card:has-text("Recent Orders")',
    lowStockAlertsCard: '.ant-card:has-text("Low Stock Alerts")',
    statValue: '.ant-statistic-content-value',
  },
  products: {
    searchInput: '.ant-input-search input, input[placeholder*="Search products"]',
    addButton: 'button:has-text("Add Product")',
    table: '.ant-table',
    rows: '.ant-table-row',
    editBtn: 'button:has-text("Edit")',
    deleteBtn: 'button:has-text("Delete"), button[aria-label="Delete"]',
    nameHeader: 'th:has-text("Name")',
    skuHeader: 'th:has-text("SKU")',
    priceHeader: 'th:has-text("Price")',
    stockHeader: 'th:has-text("Stock")',
  },
  productModal: {
    dialog: '.ant-modal:has-text("Product")',
    nameInput: '#product_name, .ant-form-item:has-text("Product Name") input',
    skuInput: '#product_sku, .ant-form-item:has-text("SKU") input',
    barcodeInput: '.ant-form-item:has-text("Barcode") input',
    sellingPriceInput: '.ant-form-item:has-text("Selling Price") .ant-input-number',
    costPriceInput: '.ant-form-item:has-text("Cost Price") .ant-input-number',
    stockInput: '.ant-form-item:has-text("Stock Quantity") .ant-input-number',
    minStockInput: '.ant-form-item:has-text("Min Stock") .ant-input-number',
    categorySelect: '.ant-form-item:has-text("Category") .ant-select',
    saveBtn: '.ant-modal:has-text("Product") button:has-text("Save"), .ant-modal:has-text("Product") button:has-text("Create")',
    cancelBtn: '.ant-modal:has-text("Product") button:has-text("Cancel")',
  },
  orders: {
    newOrderBtn: 'button:has-text("New Order")',
    table: '.ant-table',
    rows: '.ant-table-row',
    viewBtn: 'button:has-text("View")',
  },
  orderModal: {
    dialog: '.ant-modal:has-text("New Order")',
    customerSelect: '.ant-form-item:has-text("Customer") .ant-select',
    paymentSelect: '.ant-form-item:has-text("Payment") .ant-select',
    notesInput: '.ant-form-item:has-text("Notes") textarea',
    addItemBtn: 'button:has-text("Add Item")',
    completeBtn: 'button:has-text("Complete Order")',
    cancelBtn: 'button:has-text("Cancel")',
    totalText: '.ant-modal:has-text("New Order") [style*="fontWeight: bold"]',
    itemRows: '.ant-modal:has-text("New Order") .ant-table-row',
  },
  customers: {
    addButton: 'button:has-text("Add Customer")',
    table: '.ant-table',
    rows: '.ant-table-row',
    editBtn: 'button:has-text("Edit")',
  },
  customerModal: {
    dialog: '.ant-modal:has-text("Customer")',
    firstNameInput: '.ant-form-item:has-text("First Name") input',
    lastNameInput: '.ant-form-item:has-text("Last Name") input',
    emailInput: '.ant-form-item:has-text("Email") input[type="email"]',
    phoneInput: '.ant-form-item:has-text("Phone") input',
    cityInput: '.ant-form-item:has-text("City") input',
    saveBtn: '.ant-modal:has-text("Customer") button:has-text("Save"), .ant-modal:has-text("Customer") button:has-text("Create")',
  },
  inventory: {
    table: '.ant-table',
    rows: '.ant-table-row',
    adjustBtn: 'button:has-text("Adjust")',
    countBtn: 'button:has-text("Count")',
    transferBtn: 'button:has-text("Transfer")',
  },
  adjustModal: {
    dialog: '.ant-modal:has-text("Adjust Stock")',
    quantityInput: '.ant-form-item:has-text("Quantity") .ant-input-number',
    reasonInput: '.ant-form-item:has-text("Reason") input',
    saveBtn: '.ant-modal:has-text("Adjust Stock") button:has-text("Save"), .ant-modal:has-text("Adjust Stock") button:has-text("Adjust")',
  },
  staff: {
    listTab: '.ant-tabs-tab:has-text("Staff List")',
    leaderboardTab: '.ant-tabs-tab:has-text("Leaderboard")',
    table: '.ant-table',
    rows: '.ant-table-row',
  },
  reports: {
    typeSelect: '.ant-select:has-text("Sales Report"), .ant-select',
    dateRangePicker: '.ant-picker-range',
    generateBtn: 'button:has-text("Generate Report")',
    statCards: '.ant-statistic',
    table: '.ant-table',
  },
  common: {
    modal: '.ant-modal',
    modalTitle: '.ant-modal-title',
    confirmBtn: '.ant-modal-confirm-btns .ant-btn-primary, .ant-btn-primary:has-text("OK")',
    cancelBtn: '.ant-btn:not(.ant-btn-primary):has-text("Cancel")',
    loading: '.ant-spin',
    emptyState: '.ant-empty',
    pagination: '.ant-pagination',
    toast: '.ant-message-notice',
  },
} as const;

export const TENANT = {
  nav: {
    links: 'nav a, .nav-links a',
    bookingLink: 'a:has-text("Book")',
    roomsLink: 'a:has-text("Room"), a:has-text("Accommodation")',
    aboutLink: 'a:has-text("About")',
    contactLink: 'a:has-text("Contact")',
    faqLink: 'a:has-text("FAQ")',
    galleryLink: 'a:has-text("Gallery")',
    homeLink: 'a:has-text("Home"), nav a:first-child',
  },
  home: {
    heroBanner: '.hero-banner, .hero-content',
    exploreBtn: 'a:has-text("Explore Accommodations")',
    bookBtn: 'a:has-text("Book Your Stay")',
    roomsGrid: '.rooms-grid',
    roomCards: '.room-card',
    learnMoreLink: 'a:has-text("Read Our Story")',
    mapContainer: '.map-container',
  },
  booking: {
    form: '#publicBookingForm',
    guestName: '#bookGuestName',
    guestEmail: '#bookGuestEmail',
    guestPhone: '#bookGuestPhone',
    campSelect: '#bookCampId',
    roomTypeSelect: '#bookRoomTypeId',
    checkIn: '#bookCheckIn',
    checkOut: '#bookCheckOut',
    guests: '#bookPeople',
    submitBtn: '#submitBtn',
    payNowBtn: '#payNowBtn',
    availabilityStatus: '#availabilityStatus',
    paymentStatus: '#paymentStatus',
    nightlyRate: '#nightlyRateValue',
    totalNights: '#totalNightsValue',
    fees: '#feesValue',
    estimatedTotal: '#estimatedPrice',
    pricingCard: '.pricing-card',
  },
  rooms: {
    roomsList: '.rooms-list',
    roomRows: '.room-row',
    roomName: '.room-info h2',
    roomDesc: '.room-info .desc',
    bookBtn: '.room-row a:has-text("Check Availability")',
    emptyState: '.no-rooms',
  },
  about: {
    grid: '.about-grid',
    storySection: '.about-text',
    featureCards: '.feature-card',
  },
  contact: {
    form: '#contactForm',
    nameInput: '#cName',
    emailInput: '#cEmail',
    messageInput: '#cMessage',
    submitBtn: 'button:has-text("Send Message"), .submit-btn',
    infoBlocks: '.info-block',
  },
  faq: {
    accordionList: '.faq-accordion-list',
    faqItems: '.faq-item',
    questions: '.faq-question',
    answers: '.faq-answer',
    noFaqs: '.no-faqs',
  },
  gallery: {
    grid: '.gallery-grid',
    items: '.gallery-item',
    lightbox: '#lightboxModal',
    lightboxImg: '#lightboxImg',
    closeBtn: '#lightboxModal .close-btn',
    noImages: '.no-images',
  },
} as const;

export const MARKETPLACE = {
  home: {
    heroContainer: '.hero-container',
    campGrid: '#campsGrid',
    campCards: '.camp-card',
    campNames: '.camp-name',
    exploreBtn: 'a:has-text("Explore Camp")',
    filterForm: '#filterForm',
    searchInput: '#filterSearch',
    locationSelect: '#filterLocation',
    capacitySelect: '#filterCapacity',
    activitySelect: '#filterActivity',
    filterSubmit: '#filterForm button[type="submit"], button:has-text("Search")',
    onboardingForm: '#onboardingForm',
    tenantNameInput: '#tenantName',
    tenantSubdomainInput: '#tenantSubdomain',
    tenantColorInput: '#tenantColor',
    tenantLocationInput: '#tenantLocation',
    tenantActivitiesInput: '#tenantActivities',
    tenantDescInput: '#tenantDesc',
    onboardingSubmit: '#onboardingForm button[type="submit"]',
  },
  campDetail: {
    backLink: '.back-nav a',
    banner: '.banner',
    bannerTitle: '.banner-content h1',
    aboutBlock: '.about-block',
    roomsGrid: '.rooms-grid',
    roomCards: '.room-card',
    reviewsGrid: '.reviews-grid',
    reviewCards: '.review-card',
    ctaButton: '.cta-btn',
    mapContainer: '.map-container',
  },
} as const;

export const ADMIN = {
  login: {
    overlay: '#loginOverlay',
    emailInput: '#loginEmail',
    passwordInput: '#loginPassword',
    submitBtn: 'button:has-text("Sign In")',
  },
  passcode: {
    overlay: '#passcodeOverlay',
    input: '#gatewayPasscode',
    rememberCheckbox: '#rememberPasscode',
    submitBtn: 'button:has-text("Unlock Administration")',
    resetBtn: 'button:has-text("Request Passcode Reset")',
  },
  sidebar: {
    container: '#sidebar',
    superAdminNav: '#superAdminNav',
    tenantNav: '#tenantNav',
    overviewTab: 'button[data-tab="super_dashboard"], button[data-tab="dashboard"]',
    tenantsTab: 'button[data-tab="super_tenants"]',
    campsTab: 'button[data-tab="camps"]',
    roomsTab: 'button[data-tab="rooms"]',
    ratePlansTab: 'button[data-tab="rateplans"]',
    reservationsTab: 'button[data-tab="super_reservations"], button[data-tab="reservations"]',
    staffTab: 'button[data-tab="staff"]',
    expensesTab: 'button[data-tab="expenses"]',
    inventoryTab: 'button[data-tab="inventory"]',
    mealsTab: 'button[data-tab="meals"]',
    reportsTab: 'button[data-tab="reports"]',
    financialTab: 'button[data-tab="financial"]',
    settingsTab: 'button[data-tab="settings"]',
    logoutBtn: 'button:has-text("Logout")',
    backLink: '#masterAdminBackLink',
  },
  content: {
    area: '#contentArea',
    statsGrid: '.stats-grid, .analytics-grid',
    statCards: '.stat-card, .stat-val',
    tenantTable: '.tenant-table, table',
    formInputs: 'input, select, textarea',
  },
} as const;
