import type { MiddlewareHandler } from 'astro';
import { defineMiddleware } from 'astro:middleware';

/**
 * Security headers injected into every response produced by the Pages
 * Functions / SSR worker (`output: 'server'`).
 *
 * IMPORTANT: Cloudflare Pages `_headers` files only apply to STATIC assets
 * served from the Pages asset store. Responses generated by the worker
 * (`_worker.js`, i.e. every Astro SSR route) are NOT covered by `_headers`,
 * so they are injected here in middleware instead. `app/public/_headers` is
 * still kept in sync for the static-asset paths.
 *
 * CSP rationale (verified against the built HTML output):
 *  - Inline scripts are required by the Astro/React build (Fast Refresh
 *    preamble, lang-toggle cookie script, `window.__API_BASE` bootstrap,
 *    admin/POS global helpers) -> `script-src 'self' 'unsafe-inline'`.
 *  - Inline <style> blocks are required by AdminLayout / POSLayout / book &
 *    menu pages + Google Fonts stylesheet -> `style-src 'self' 'unsafe-inline'
 *    https://fonts.googleapis.com`.
 *  - Tenant data can reference arbitrary https image hosts (images.unsplash.com,
 *    i.postimg.cc, ...) and `normalizeAssetUrl` upgrades http->https ->
 *    `img-src 'self' data: https:`.
 *  - API is same-origin on sinaicamps.com (`/api`) or
 *    `https://sinaicamps.com/api` for custom-domain tenants ->
 *    `connect-src 'self' https://sinaicamps.com https://*.sinaicamps.com`.
 *  - Plausible analytics: the `script.tagged-events.js` loader is injected by
 *    PublicLayout/AdminLayout from `https://plausible.io` and posts events to
 *    `https://plausible.io/api/event` -> `https://plausible.io` is allow-listed
 *    in both `script-src` and `connect-src`.
 *  - Google Maps is embedded via tenant `map_embed_url` ->
 *    `frame-src https://www.google.com https://*.google.com
 *    https://www.openstreetmap.org https://*.openstreetmap.org`.
 *  - The site is never framed itself -> `X-Frame-Options: DENY` +
 *    `frame-ancestors 'none'`.
 */

const LOCAL_HOSTS = ['localhost', '127.0.0.1'];

const PROD_CSP = [
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline' https://plausible.io",
  "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
  "img-src 'self' data: https:",
  "font-src 'self' https://fonts.gstatic.com",
  "connect-src 'self' https://sinaicamps.com https://*.sinaicamps.com https://plausible.io",
  "frame-src https://www.google.com https://*.google.com https://www.openstreetmap.org https://*.openstreetmap.org",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
].join('; ');

/**
 * Local dev CSP — the admin/POS SPAs call the local backend directly. Only the
 * `connect-src` origin differs from PROD; the replace keeps the trailing
 * `https://plausible.io` allow-list so the analytics loader works identically
 * in dev.
 */
const DEV_CSP = PROD_CSP.replace(
  "connect-src 'self' https://sinaicamps.com https://*.sinaicamps.com",
  "connect-src 'self' http://localhost:8787 http://127.0.0.1:8787",
);

function isLocalHost(hostname: string): boolean {
  return (
    LOCAL_HOSTS.includes(hostname) ||
    hostname.endsWith('.localhost') ||
    hostname.endsWith('.127.0.0.1')
  );
}

export function buildSecurityHeaders(hostname: string): Record<string, string> {
  return {
    'X-Frame-Options': 'DENY',
    'X-Content-Type-Options': 'nosniff',
    'Referrer-Policy': 'strict-origin-when-cross-origin',
    'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
    'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',
    'Content-Security-Policy': isLocalHost(hostname) ? DEV_CSP : PROD_CSP,
  };
}

export const onRequest: MiddlewareHandler = defineMiddleware(async (context, next) => {
  const response = await next();
  if (!response) return response;

  const headers = buildSecurityHeaders(context.url.hostname);
  for (const [name, value] of Object.entries(headers)) {
    response.headers.set(name, value);
  }
  return response;
});
